### PR TITLE
new commit: * dev: Пт 15 июл 2022 15:11:46 MSK

### PR DESCRIPTION
**Pull request by ann1221**
- [x] - rename commit message

### CODE REVIEW

**Comment by aritmos-company-account** [comment]
- [ ] - check comment by yourself
- [ ] - send self e-mail

**Comment by ann1221** [comment]
> * some comment some comment some comment

i comment some comment

**Comment by ann1221** [comment]
> * another comment
>       another comment
>       another commnet

**Comment by ann1221** [comment]
> * another comment
>       another comment
>       another commnet

i comment another comment

**Review by aritmos-company-account — COMMENTED** [review]
update commit message

**Comment by aritmos-company-account** [comment]
- [ ] add 1 extra log

**Pull request closed without merging**
